/**
 * generated by Xtext 2.23.0
 */
package org.xtext.example.mydsl.generator;

/**
 * Generates code from your model files on save.
 * 
 * See https://www.eclipse.org/Xtext/documentation/303_runtime_concepts.html#code-generation
 */
@SuppressWarnings("all")
public class FieldPossessor {
  public static int index = 0;
  
  public static void increment() {
    FieldPossessor.index++;
  }
  
  public static void decrement() {
    FieldPossessor.index--;
  }
}
