/**
 * generated by Xtext 2.23.0
 */
package org.xtext.example.mydsl.jsonDsl;

import org.eclipse.emf.common.util.EList;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Add</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link org.xtext.example.mydsl.jsonDsl.Add#getValue <em>Value</em>}</li>
 *   <li>{@link org.xtext.example.mydsl.jsonDsl.Add#getVariable <em>Variable</em>}</li>
 *   <li>{@link org.xtext.example.mydsl.jsonDsl.Add#getFields <em>Fields</em>}</li>
 * </ul>
 *
 * @see org.xtext.example.mydsl.jsonDsl.JsonDslPackage#getAdd()
 * @model
 * @generated
 */
public interface Add extends FunctionCall
{
  /**
   * Returns the value of the '<em><b>Value</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Value</em>' containment reference.
   * @see #setValue(Expression)
   * @see org.xtext.example.mydsl.jsonDsl.JsonDslPackage#getAdd_Value()
   * @model containment="true"
   * @generated
   */
  Expression getValue();

  /**
   * Sets the value of the '{@link org.xtext.example.mydsl.jsonDsl.Add#getValue <em>Value</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Value</em>' containment reference.
   * @see #getValue()
   * @generated
   */
  void setValue(Expression value);

  /**
   * Returns the value of the '<em><b>Variable</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Variable</em>' containment reference.
   * @see #setVariable(Expression)
   * @see org.xtext.example.mydsl.jsonDsl.JsonDslPackage#getAdd_Variable()
   * @model containment="true"
   * @generated
   */
  Expression getVariable();

  /**
   * Sets the value of the '{@link org.xtext.example.mydsl.jsonDsl.Add#getVariable <em>Variable</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Variable</em>' containment reference.
   * @see #getVariable()
   * @generated
   */
  void setVariable(Expression value);

  /**
   * Returns the value of the '<em><b>Fields</b></em>' attribute list.
   * The list contents are of type {@link java.lang.String}.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Fields</em>' attribute list.
   * @see org.xtext.example.mydsl.jsonDsl.JsonDslPackage#getAdd_Fields()
   * @model unique="false"
   * @generated
   */
  EList<String> getFields();

} // Add
