/**
 * generated by Xtext 2.23.0
 */
package org.xtext.example.mydsl.jsonDsl;

import org.eclipse.emf.common.util.EList;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Add</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link org.xtext.example.mydsl.jsonDsl.Add#getExpression <em>Expression</em>}</li>
 *   <li>{@link org.xtext.example.mydsl.jsonDsl.Add#getVariable <em>Variable</em>}</li>
 *   <li>{@link org.xtext.example.mydsl.jsonDsl.Add#getFields <em>Fields</em>}</li>
 * </ul>
 *
 * @see org.xtext.example.mydsl.jsonDsl.JsonDslPackage#getAdd()
 * @model
 * @generated
 */
public interface Add extends AlterFunctions
{
  /**
   * Returns the value of the '<em><b>Expression</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Expression</em>' containment reference.
   * @see #setExpression(Expression)
   * @see org.xtext.example.mydsl.jsonDsl.JsonDslPackage#getAdd_Expression()
   * @model containment="true"
   * @generated
   */
  Expression getExpression();

  /**
   * Sets the value of the '{@link org.xtext.example.mydsl.jsonDsl.Add#getExpression <em>Expression</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Expression</em>' containment reference.
   * @see #getExpression()
   * @generated
   */
  void setExpression(Expression value);

  /**
   * Returns the value of the '<em><b>Variable</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Variable</em>' containment reference.
   * @see #setVariable(Expression)
   * @see org.xtext.example.mydsl.jsonDsl.JsonDslPackage#getAdd_Variable()
   * @model containment="true"
   * @generated
   */
  Expression getVariable();

  /**
   * Sets the value of the '{@link org.xtext.example.mydsl.jsonDsl.Add#getVariable <em>Variable</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Variable</em>' containment reference.
   * @see #getVariable()
   * @generated
   */
  void setVariable(Expression value);

  /**
   * Returns the value of the '<em><b>Fields</b></em>' containment reference list.
   * The list contents are of type {@link org.xtext.example.mydsl.jsonDsl.Expression}.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Fields</em>' containment reference list.
   * @see org.xtext.example.mydsl.jsonDsl.JsonDslPackage#getAdd_Fields()
   * @model containment="true"
   * @generated
   */
  EList<Expression> getFields();

} // Add
