/**
 * generated by Xtext 2.23.0
 */
package org.xtext.example.mydsl.jsonDsl;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Array Specifier</b></em>'.
 * <!-- end-user-doc -->
 *
 *
 * @see org.xtext.example.mydsl.jsonDsl.JsonDslPackage#getArraySpecifier()
 * @model
 * @generated
 */
public interface ArraySpecifier extends EObject
{
} // ArraySpecifier
