/**
 * generated by Xtext 2.23.0
 */
package org.xtext.example.mydsl.jsonDsl;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Auxiliar Caller</b></em>'.
 * <!-- end-user-doc -->
 *
 *
 * @see org.xtext.example.mydsl.jsonDsl.JsonDslPackage#getAuxiliarCaller()
 * @model
 * @generated
 */
public interface AuxiliarCaller extends EObject
{
} // AuxiliarCaller
