/**
 * generated by Xtext 2.23.0
 */
package org.xtext.example.mydsl.jsonDsl;


/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Binary Expression</b></em>'.
 * <!-- end-user-doc -->
 *
 *
 * @see org.xtext.example.mydsl.jsonDsl.JsonDslPackage#getBinaryExpression()
 * @model
 * @generated
 */
public interface BinaryExpression extends Expression
{
} // BinaryExpression
