/**
 * generated by Xtext 2.23.0
 */
package org.xtext.example.mydsl.jsonDsl;


/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Extract</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link org.xtext.example.mydsl.jsonDsl.Extract#getValue <em>Value</em>}</li>
 *   <li>{@link org.xtext.example.mydsl.jsonDsl.Extract#getAuxiliar <em>Auxiliar</em>}</li>
 * </ul>
 *
 * @see org.xtext.example.mydsl.jsonDsl.JsonDslPackage#getExtract()
 * @model
 * @generated
 */
public interface Extract extends FunctionCall
{
  /**
   * Returns the value of the '<em><b>Value</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Value</em>' containment reference.
   * @see #setValue(Expression)
   * @see org.xtext.example.mydsl.jsonDsl.JsonDslPackage#getExtract_Value()
   * @model containment="true"
   * @generated
   */
  Expression getValue();

  /**
   * Sets the value of the '{@link org.xtext.example.mydsl.jsonDsl.Extract#getValue <em>Value</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Value</em>' containment reference.
   * @see #getValue()
   * @generated
   */
  void setValue(Expression value);

  /**
   * Returns the value of the '<em><b>Auxiliar</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Auxiliar</em>' containment reference.
   * @see #setAuxiliar(ArithmeticAuxiliar)
   * @see org.xtext.example.mydsl.jsonDsl.JsonDslPackage#getExtract_Auxiliar()
   * @model containment="true"
   * @generated
   */
  ArithmeticAuxiliar getAuxiliar();

  /**
   * Sets the value of the '{@link org.xtext.example.mydsl.jsonDsl.Extract#getAuxiliar <em>Auxiliar</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Auxiliar</em>' containment reference.
   * @see #getAuxiliar()
   * @generated
   */
  void setAuxiliar(ArithmeticAuxiliar value);

} // Extract
