/**
 * generated by Xtext 2.23.0
 */
package org.xtext.example.mydsl.jsonDsl;


/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>IO Functions</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link org.xtext.example.mydsl.jsonDsl.IOFunctions#getFileName <em>File Name</em>}</li>
 * </ul>
 *
 * @see org.xtext.example.mydsl.jsonDsl.JsonDslPackage#getIOFunctions()
 * @model
 * @generated
 */
public interface IOFunctions extends Expression
{
  /**
   * Returns the value of the '<em><b>File Name</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>File Name</em>' containment reference.
   * @see #setFileName(Expression)
   * @see org.xtext.example.mydsl.jsonDsl.JsonDslPackage#getIOFunctions_FileName()
   * @model containment="true"
   * @generated
   */
  Expression getFileName();

  /**
   * Sets the value of the '{@link org.xtext.example.mydsl.jsonDsl.IOFunctions#getFileName <em>File Name</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>File Name</em>' containment reference.
   * @see #getFileName()
   * @generated
   */
  void setFileName(Expression value);

} // IOFunctions
