/**
 * generated by Xtext 2.23.0
 */
package org.xtext.example.mydsl.jsonDsl;


/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Manip Functions</b></em>'.
 * <!-- end-user-doc -->
 *
 *
 * @see org.xtext.example.mydsl.jsonDsl.JsonDslPackage#getManipFunctions()
 * @model
 * @generated
 */
public interface ManipFunctions extends Expression
{
} // ManipFunctions
