/**
 * generated by Xtext 2.23.0
 */
package org.xtext.example.mydsl.jsonDsl;


/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Sum</b></em>'.
 * <!-- end-user-doc -->
 *
 *
 * @see org.xtext.example.mydsl.jsonDsl.JsonDslPackage#getSum()
 * @model
 * @generated
 */
public interface Sum extends ArithFunctions
{
} // Sum
