/**
 * generated by Xtext 2.23.0
 */
package org.xtext.example.mydsl.jsonDsl;

import org.eclipse.emf.common.util.EList;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Variable Call</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link org.xtext.example.mydsl.jsonDsl.VariableCall#getName <em>Name</em>}</li>
 *   <li>{@link org.xtext.example.mydsl.jsonDsl.VariableCall#getCaller <em>Caller</em>}</li>
 * </ul>
 *
 * @see org.xtext.example.mydsl.jsonDsl.JsonDslPackage#getVariableCall()
 * @model
 * @generated
 */
public interface VariableCall extends Expression
{
  /**
   * Returns the value of the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Name</em>' attribute.
   * @see #setName(String)
   * @see org.xtext.example.mydsl.jsonDsl.JsonDslPackage#getVariableCall_Name()
   * @model
   * @generated
   */
  String getName();

  /**
   * Sets the value of the '{@link org.xtext.example.mydsl.jsonDsl.VariableCall#getName <em>Name</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Name</em>' attribute.
   * @see #getName()
   * @generated
   */
  void setName(String value);

  /**
   * Returns the value of the '<em><b>Caller</b></em>' containment reference list.
   * The list contents are of type {@link org.xtext.example.mydsl.jsonDsl.AuxiliarCaller}.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Caller</em>' containment reference list.
   * @see org.xtext.example.mydsl.jsonDsl.JsonDslPackage#getVariableCall_Caller()
   * @model containment="true"
   * @generated
   */
  EList<AuxiliarCaller> getCaller();

} // VariableCall
