/**
 * generated by Xtext 2.23.0
 */
package org.xtext.example.mydsl.jsonDsl.impl;

import org.eclipse.emf.ecore.EClass;

import org.xtext.example.mydsl.jsonDsl.JsonDslPackage;
import org.xtext.example.mydsl.jsonDsl.ManipFunctions;

/**
 * <!-- begin-user-doc -->
 * An implementation of the model object '<em><b>Manip Functions</b></em>'.
 * <!-- end-user-doc -->
 *
 * @generated
 */
public class ManipFunctionsImpl extends ExpressionImpl implements ManipFunctions
{
  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  protected ManipFunctionsImpl()
  {
    super();
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  protected EClass eStaticClass()
  {
    return JsonDslPackage.Literals.MANIP_FUNCTIONS;
  }

} //ManipFunctionsImpl
