/**
 * generated by Xtext 2.23.0
 */
package org.xtext.example.mydsl.jsonDsl.impl;

import org.eclipse.emf.ecore.EClass;

import org.xtext.example.mydsl.jsonDsl.JsonDslPackage;
import org.xtext.example.mydsl.jsonDsl.Mean;

/**
 * <!-- begin-user-doc -->
 * An implementation of the model object '<em><b>Mean</b></em>'.
 * <!-- end-user-doc -->
 *
 * @generated
 */
public class MeanImpl extends ArithFunctionsImpl implements Mean
{
  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  protected MeanImpl()
  {
    super();
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  protected EClass eStaticClass()
  {
    return JsonDslPackage.Literals.MEAN;
  }

} //MeanImpl
