/**
 * generated by Xtext 2.23.0
 */
package org.xtext.example.mydsl.jsonDsl.impl;

import org.eclipse.emf.common.notify.Notification;

import org.eclipse.emf.ecore.EClass;

import org.eclipse.emf.ecore.impl.ENotificationImpl;

import org.xtext.example.mydsl.jsonDsl.JsonDslPackage;
import org.xtext.example.mydsl.jsonDsl.Primitive;

/**
 * <!-- begin-user-doc -->
 * An implementation of the model object '<em><b>Primitive</b></em>'.
 * <!-- end-user-doc -->
 * <p>
 * The following features are implemented:
 * </p>
 * <ul>
 *   <li>{@link org.xtext.example.mydsl.jsonDsl.impl.PrimitiveImpl#getStr <em>Str</em>}</li>
 *   <li>{@link org.xtext.example.mydsl.jsonDsl.impl.PrimitiveImpl#getIntNum <em>Int Num</em>}</li>
 *   <li>{@link org.xtext.example.mydsl.jsonDsl.impl.PrimitiveImpl#getFloatNum <em>Float Num</em>}</li>
 *   <li>{@link org.xtext.example.mydsl.jsonDsl.impl.PrimitiveImpl#getBool <em>Bool</em>}</li>
 *   <li>{@link org.xtext.example.mydsl.jsonDsl.impl.PrimitiveImpl#getNil <em>Nil</em>}</li>
 * </ul>
 *
 * @generated
 */
public class PrimitiveImpl extends ConstantImpl implements Primitive
{
  /**
   * The default value of the '{@link #getStr() <em>Str</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getStr()
   * @generated
   * @ordered
   */
  protected static final String STR_EDEFAULT = null;

  /**
   * The cached value of the '{@link #getStr() <em>Str</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getStr()
   * @generated
   * @ordered
   */
  protected String str = STR_EDEFAULT;

  /**
   * The default value of the '{@link #getIntNum() <em>Int Num</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getIntNum()
   * @generated
   * @ordered
   */
  protected static final int INT_NUM_EDEFAULT = 0;

  /**
   * The cached value of the '{@link #getIntNum() <em>Int Num</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getIntNum()
   * @generated
   * @ordered
   */
  protected int intNum = INT_NUM_EDEFAULT;

  /**
   * The default value of the '{@link #getFloatNum() <em>Float Num</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getFloatNum()
   * @generated
   * @ordered
   */
  protected static final String FLOAT_NUM_EDEFAULT = null;

  /**
   * The cached value of the '{@link #getFloatNum() <em>Float Num</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getFloatNum()
   * @generated
   * @ordered
   */
  protected String floatNum = FLOAT_NUM_EDEFAULT;

  /**
   * The default value of the '{@link #getBool() <em>Bool</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getBool()
   * @generated
   * @ordered
   */
  protected static final String BOOL_EDEFAULT = null;

  /**
   * The cached value of the '{@link #getBool() <em>Bool</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getBool()
   * @generated
   * @ordered
   */
  protected String bool = BOOL_EDEFAULT;

  /**
   * The default value of the '{@link #getNil() <em>Nil</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getNil()
   * @generated
   * @ordered
   */
  protected static final String NIL_EDEFAULT = null;

  /**
   * The cached value of the '{@link #getNil() <em>Nil</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getNil()
   * @generated
   * @ordered
   */
  protected String nil = NIL_EDEFAULT;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  protected PrimitiveImpl()
  {
    super();
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  protected EClass eStaticClass()
  {
    return JsonDslPackage.Literals.PRIMITIVE;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public String getStr()
  {
    return str;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void setStr(String newStr)
  {
    String oldStr = str;
    str = newStr;
    if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, JsonDslPackage.PRIMITIVE__STR, oldStr, str));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public int getIntNum()
  {
    return intNum;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void setIntNum(int newIntNum)
  {
    int oldIntNum = intNum;
    intNum = newIntNum;
    if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, JsonDslPackage.PRIMITIVE__INT_NUM, oldIntNum, intNum));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public String getFloatNum()
  {
    return floatNum;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void setFloatNum(String newFloatNum)
  {
    String oldFloatNum = floatNum;
    floatNum = newFloatNum;
    if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, JsonDslPackage.PRIMITIVE__FLOAT_NUM, oldFloatNum, floatNum));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public String getBool()
  {
    return bool;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void setBool(String newBool)
  {
    String oldBool = bool;
    bool = newBool;
    if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, JsonDslPackage.PRIMITIVE__BOOL, oldBool, bool));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public String getNil()
  {
    return nil;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void setNil(String newNil)
  {
    String oldNil = nil;
    nil = newNil;
    if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, JsonDslPackage.PRIMITIVE__NIL, oldNil, nil));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public Object eGet(int featureID, boolean resolve, boolean coreType)
  {
    switch (featureID)
    {
      case JsonDslPackage.PRIMITIVE__STR:
        return getStr();
      case JsonDslPackage.PRIMITIVE__INT_NUM:
        return getIntNum();
      case JsonDslPackage.PRIMITIVE__FLOAT_NUM:
        return getFloatNum();
      case JsonDslPackage.PRIMITIVE__BOOL:
        return getBool();
      case JsonDslPackage.PRIMITIVE__NIL:
        return getNil();
    }
    return super.eGet(featureID, resolve, coreType);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void eSet(int featureID, Object newValue)
  {
    switch (featureID)
    {
      case JsonDslPackage.PRIMITIVE__STR:
        setStr((String)newValue);
        return;
      case JsonDslPackage.PRIMITIVE__INT_NUM:
        setIntNum((Integer)newValue);
        return;
      case JsonDslPackage.PRIMITIVE__FLOAT_NUM:
        setFloatNum((String)newValue);
        return;
      case JsonDslPackage.PRIMITIVE__BOOL:
        setBool((String)newValue);
        return;
      case JsonDslPackage.PRIMITIVE__NIL:
        setNil((String)newValue);
        return;
    }
    super.eSet(featureID, newValue);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void eUnset(int featureID)
  {
    switch (featureID)
    {
      case JsonDslPackage.PRIMITIVE__STR:
        setStr(STR_EDEFAULT);
        return;
      case JsonDslPackage.PRIMITIVE__INT_NUM:
        setIntNum(INT_NUM_EDEFAULT);
        return;
      case JsonDslPackage.PRIMITIVE__FLOAT_NUM:
        setFloatNum(FLOAT_NUM_EDEFAULT);
        return;
      case JsonDslPackage.PRIMITIVE__BOOL:
        setBool(BOOL_EDEFAULT);
        return;
      case JsonDslPackage.PRIMITIVE__NIL:
        setNil(NIL_EDEFAULT);
        return;
    }
    super.eUnset(featureID);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public boolean eIsSet(int featureID)
  {
    switch (featureID)
    {
      case JsonDslPackage.PRIMITIVE__STR:
        return STR_EDEFAULT == null ? str != null : !STR_EDEFAULT.equals(str);
      case JsonDslPackage.PRIMITIVE__INT_NUM:
        return intNum != INT_NUM_EDEFAULT;
      case JsonDslPackage.PRIMITIVE__FLOAT_NUM:
        return FLOAT_NUM_EDEFAULT == null ? floatNum != null : !FLOAT_NUM_EDEFAULT.equals(floatNum);
      case JsonDslPackage.PRIMITIVE__BOOL:
        return BOOL_EDEFAULT == null ? bool != null : !BOOL_EDEFAULT.equals(bool);
      case JsonDslPackage.PRIMITIVE__NIL:
        return NIL_EDEFAULT == null ? nil != null : !NIL_EDEFAULT.equals(nil);
    }
    return super.eIsSet(featureID);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public String toString()
  {
    if (eIsProxy()) return super.toString();

    StringBuilder result = new StringBuilder(super.toString());
    result.append(" (str: ");
    result.append(str);
    result.append(", intNum: ");
    result.append(intNum);
    result.append(", floatNum: ");
    result.append(floatNum);
    result.append(", bool: ");
    result.append(bool);
    result.append(", nil: ");
    result.append(nil);
    result.append(')');
    return result.toString();
  }

} //PrimitiveImpl
