/**
 * generated by Xtext 2.23.0
 */
package org.xtext.example.mydsl.jsonDsl.impl;

import org.eclipse.emf.ecore.EClass;

import org.eclipse.emf.ecore.impl.MinimalEObjectImpl;

import org.xtext.example.mydsl.jsonDsl.JsonDslPackage;
import org.xtext.example.mydsl.jsonDsl.SimpleStatement;

/**
 * <!-- begin-user-doc -->
 * An implementation of the model object '<em><b>Simple Statement</b></em>'.
 * <!-- end-user-doc -->
 *
 * @generated
 */
public class SimpleStatementImpl extends MinimalEObjectImpl.Container implements SimpleStatement
{
  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  protected SimpleStatementImpl()
  {
    super();
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  protected EClass eStaticClass()
  {
    return JsonDslPackage.Literals.SIMPLE_STATEMENT;
  }

} //SimpleStatementImpl
